name: Deploy to release branch

env:
  GITHUB_TOKEN: ${{ github.token }}

on:
  # Triggers the workflow on push or pull request events but only for dev branch
  pull_request:
    branches:
      - main
    types:
      - closed

#permissions:
#  contents: read
#  pull-requests: read

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update your release branch
        uses: zesticio/update-release-branch@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: 'deebendu.kumar@zestic.in'
          source_file: "."
          username: ${{ github.actor }}
          destination_repo: 'zesticio/st-crm-template'
          destination_branch: 'release'
          commit_message: ${{ github.ref }}